name: hello action
on: 
 push: 
   branches:
    - main 
 pull_request:
 schedule: 
  - cron: "0 0 * * *"

jobs:
   helloaction:
     runs-on: ubuntu-latest
     steps:
      - name: hello action
        run: echo "hello-action"
